/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#e3e2df',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#f2f1ed',
        'on-tertiary-container': '#85847f',
        'on-background': '#1b1c1a',
        'on-tertiary-fixed': '#1c1c18',
        'surface-container-low': '#f4f4f0',
        'outline-variant': '#c4c7c7',
        'surface': '#faf9f5',
        'secondary-container': '#fed488',
        'error-container': '#ffdad6',
        'surface-variant': '#e3e2df',
        'primary-fixed': '#e5e2e1',
        'tertiary-fixed-dim': '#c9c6c1',
        'on-secondary-container': '#785a1a',
        'inverse-surface': '#2f312e',
        'inverse-primary': '#c8c6c5',
        'on-primary-fixed-variant': '#474746',
        'on-surface': '#1b1c1a',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#261900',
        'on-error-container': '#93000a',
        'surface-container-lowest': '#ffffff',
        'secondary': '#775a19',
        'gold-accent': '#C5A059',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#c8c6c5',
        'secondary-fixed': '#ffdea5',
        'on-primary-container': '#858383',
        'tertiary-fixed': '#e5e2dc',
        'outline': '#747878',
        'on-tertiary-fixed-variant': '#474743',
        'background': '#faf9f5',
        'primary-container': '#1c1b1b',
        'surface-tint': '#5f5e5e',
        'tertiary': '#000000',
        'error': '#ba1a1a',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#5d4201',
        'on-primary-fixed': '#1c1b1b',
        'surface-container': '#efeeea',
        'on-surface-variant': '#444748',
        'surface-bright': '#faf9f5',
        'secondary-fixed-dim': '#e9c176',
        'primary': '#000000',
        'surface-container-high': '#e9e8e4',
        'tertiary-container': '#1c1c18',
        'surface-dim': '#dbdad6',
        'inverse-on-surface': '#f2f1ed',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#785a1a',
        'secondary-fixed': '#ffdea5',
        'secondary-fixed-dim': '#e9c176',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        margin: '3rem',
        'space-xl': '6rem',
        'space-xs': '0.375rem',
        'space-lg': '3rem',
        'space-md': '1.5rem',
        gutter: '2rem',
        'space-sm': '0.75rem',
      },
      fontFamily: {
        'bodoni': ['"Bodoni Moda"', 'serif'],
        'jakarta': ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['56px', { lineHeight: '64px', letterSpacing: '0.05em', fontWeight: '300' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '0.04em', fontWeight: '300' }],
        'headline-md': ['28px', { lineHeight: '36px', letterSpacing: '0.03em', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '0.02em', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '0.01em', fontWeight: '300' }],
        'body-md': ['15px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '500' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.1em', fontWeight: '500' }],
      },
      keyframes: {
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'slide-up': { from: { opacity: '0', transform: 'translateY(20px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'pulse-ring': {
          to: { boxShadow: '0 0 0 6px rgba(119, 90, 25, 0)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.4s ease-out',
        'slide-up': 'slide-up 0.5s ease-out',
        'pulse-ring': 'pulse-ring 2s infinite cubic-bezier(0.66, 0, 0, 1)',
      },
    },
  },
  plugins: [],
}
